// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaDev_JC.Models.Data;

#nullable disable

namespace PruebaDev_JC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaDev_JC.Models.Entities.ConsultaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdConsulta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime");

                    b.Property<string>("IpConsulta")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("IP_de_Consulta");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Meses")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorCuota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ConsultaLog", (string)null);
                });

            modelBuilder.Entity("PruebaDev_JC.Models.Entities.TasaEdad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<decimal>("Tasa")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("TasasEdad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Edad = 18,
                            Tasa = 1.20m
                        },
                        new
                        {
                            Id = 2,
                            Edad = 19,
                            Tasa = 1.18m
                        },
                        new
                        {
                            Id = 3,
                            Edad = 20,
                            Tasa = 1.16m
                        },
                        new
                        {
                            Id = 4,
                            Edad = 21,
                            Tasa = 1.14m
                        },
                        new
                        {
                            Id = 5,
                            Edad = 22,
                            Tasa = 1.12m
                        },
                        new
                        {
                            Id = 6,
                            Edad = 23,
                            Tasa = 1.10m
                        },
                        new
                        {
                            Id = 7,
                            Edad = 24,
                            Tasa = 1.08m
                        },
                        new
                        {
                            Id = 8,
                            Edad = 25,
                            Tasa = 1.05m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
